# Generated by Django 5.2.1 on 2025-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
