# Generated by Django 5.2.1 on 2025-06-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_detalleventa_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_anterior',
            new_name='precio_oferta',
        ),
    ]
