# Generated by Django 5.2.1 on 2025-07-02 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_aceptada_por_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-prioridad', '-fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_preparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='notas_preparacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='preparado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='preparado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_preparados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='ubicacion_bodega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_limite_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('preparada', 'Preparada'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
